import { test, expect } from 'playwright/test';
import { makeDefaultConfigV3 } from '../src/services/schedulerV3Service.ts';
const url=process.env.E2E_BASE_URL||'http://127.0.0.1:5187';
test.setTimeout(60_000);
for (const width of [390,1440]) test(`V3 draft and settings at ${width}px`,async({page},info)=>{
  const pageErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));
  await page.setViewportSize({width,height:900});
  await page.goto(url);await page.waitForFunction(()=>window.__gasStationSchedulerStore);
  const config=makeDefaultConfigV3('tenant-a');
  config.shiftTemplates.push({...config.shiftTemplates[0],id:'afternoon',label:'Απόγευμα',shiftType:'AFTERNOON',startTime:'16:00',endTime:'20:00',durationHours:4});
  await page.evaluate(config=>{
    const store=window.__gasStationSchedulerStore;store.getState().cleanupData();
    store.setState({isAdmin:true,adminUser:{uid:'test-owner',tenantId:'tenant-a'},isLoading:false,isAuthLoading:false,schedulerSchemaVersion:3,schedulerConfigV3:config,employees:[{id:'a',fullName:'Μαρία',isActive:true},{id:'b',fullName:'Νίκος',isActive:true},{id:'inactive',fullName:'Ανενεργός',isActive:false,email:'PRIVATE_EMAIL',phone:'PRIVATE_PHONE',afm:'PRIVATE_AFM'}],absences:[]});
  },config);
  const workspace=page.getByTestId('scheduler-v3-workspace');await expect(workspace).toBeVisible();
  await workspace.getByLabel('Ημερομηνία',{exact:true}).fill('2026-09-07');await workspace.getByRole('button',{name:'Δημιουργία',exact:true}).click();
  await expect(page.getByText('Προσχέδιο — επεξεργασία πριν τη δημοσίευση')).toBeVisible();
  await expect(page.getByRole('button',{name:'Αφαίρεση βάρδιας'})).toHaveCount(6);
  await page.getByRole('button',{name:'Αφαίρεση βάρδιας'}).first().click();
  await expect(page.getByRole('region', { name: 'Προειδοποιήσεις', exact: true })).toContainText('Κάλυψη 0/1');
  await expect(page.getByRole('button',{name:'Αποθήκευση προσχεδίου'})).toBeEnabled();
  await expect(page.getByRole('button',{name:'Δημοσίευση νέας έκδοσης'})).toBeDisabled();
  await page.getByLabel('Διάβασα τις προειδοποιήσεις και επιλέγω δημοσίευση.').check();
  await expect(page.getByRole('button',{name:'Δημοσίευση νέας έκδοσης'})).toBeEnabled();
  await page.getByText('Ρυθμίσεις και προφίλ εργαζομένων',{exact:true}).click();
  await expect(page.getByRole('form',{name:'Ρυθμίσεις προγράμματος V3'})).toBeVisible();
  await page.getByRole('button',{name:'Προσθήκη βάρδιας',exact:true}).click();
  await expect(page.getByRole('button',{name:'Διαγραφή Νέα βάρδια'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
  await workspace.screenshot({path:info.outputPath(`v3-${width}.png`)});
  await page.getByText('Προηγούμενα προγράμματα και εργαλεία',{exact:true}).click();
  await expect(page.getByText('Πίνακας Ανακοινώσεων',{exact:true})).toBeVisible();
  await expect(workspace.getByRole('button',{name:'Αφαίρεση βάρδιας'})).toHaveCount(5);
  const legacyWriteResults=await page.evaluate(async()=>{
    const state=window.__gasStationSchedulerStore.getState();
    return [await state.refreshPublicWeekSnapshot(),await state.refreshPublicMonthSnapshot({year:2026,month:8}),await state.clearMonthShifts({year:2026,month:8})];
  });
  expect(legacyWriteResults).toEqual([false,false,false]);
  await workspace.getByRole('button',{name:'+ Προσθήκη εργαζομένου',exact:true}).click();
  await expect(workspace.getByRole('button',{name:'Αφαίρεση βάρδιας'})).toHaveCount(5);
  const add=workspace.getByRole('group',{name:'Νέα ανάθεση',exact:true});
  const employeePicker=add.getByRole('combobox',{name:'Εργαζόμενος',exact:true});
  const startPicker=add.getByRole('combobox',{name:'Από',exact:true});
  await expect(employeePicker).toBeVisible();
  await expect(employeePicker.locator('option[value="inactive"]')).toHaveCount(0);
  await expect(startPicker.locator('option')).toHaveCount(96);
  expect(await startPicker.locator('option').allTextContents()).toEqual(Array.from({length:96},(_,i)=>`${String(Math.floor(i/4)).padStart(2,'0')}:${String(i%4*15).padStart(2,'0')}`));
  await expect(add.getByRole('textbox')).toHaveCount(0);
  await employeePicker.selectOption('b');
  await startPicker.selectOption('09:15');
  await add.getByRole('combobox',{name:'Έως',exact:true}).selectOption('17:15');
  await add.getByRole('button',{name:'Προσθήκη',exact:true}).click();
  await expect(workspace.getByRole('button',{name:'Αφαίρεση βάρδιας'})).toHaveCount(6);
  await expect(workspace.getByLabel('Εναλλακτική βάρδια',{exact:true})).toHaveCount(0);
  await expect(workspace.getByLabel('Εβδομάδα αναφοράς',{exact:true})).toHaveCount(0);
  await page.evaluate(async()=>{
    const {schedulePublicationsRepository:repo}=await import('/src/repositories/schedulePublicationsRepository.ts');
    repo.saveSettings=async(config,profiles)=>{window.__savedV3Profiles=profiles;};
  });
  const maria=workspace.getByRole('group',{name:'Μαρία',exact:true});
  await maria.getByRole('combobox',{name:'Τυπική βάρδια',exact:true}).selectOption('day');
  await maria.getByLabel('Αλλαγή βάρδιας κάθε εβδομάδα').check();
  await workspace.getByRole('button',{name:'Αποθήκευση ρυθμίσεων',exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>window.__savedV3Profiles?.find(e=>e.id==='a')?.schedulerV3.rotationAlternateShiftTemplateId)).toBe('afternoon');
  expect(await page.evaluate(()=>window.__savedV3Profiles.find(e=>e.id==='a').schedulerV3.rotationAnchorWeekStart)).toBe('2026-01-05');
  await page.evaluate(async()=>{
    const service=await import('/src/services/schedulerV3Service.ts');const publication=await import('/src/services/schedulePublicationService.ts');
    const {schedulePublicationsRepository:repo}=await import('/src/repositories/schedulePublicationsRepository.ts');
    const state=window.__gasStationSchedulerStore.getState();
    const d=service.createDraftV3({config:state.schedulerConfigV3,employees:service.mapEmployeesV3(state.employees),absences:[],periodType:'WEEK',periodStart:'2026-09-07',periodEnd:'2026-09-13',options:{balanceWeeklyTargets:true}},'history-fixture');
    window.__historyV3=publication.buildPublicationV3(d,{tenantId:'tenant-a',uid:'PRIVATE_AUTH_UID',id:'v1',version:1,timestamp:'2026-09-09T10:00:00Z'});
    window.__originalHistory=JSON.stringify(window.__historyV3);
    repo.list=async()=>[window.__historyV3];repo.listDrafts=async()=>[];
    repo.download=async()=>new TextEncoder().encode('%PDF-1.4 test history').buffer;
  });
  await workspace.getByRole('button',{name:'Φόρτωση ιστορικού'}).click();
  const history=workspace.getByRole('region',{name:'Ιστορικό δημοσιεύσεων',exact:true});
  await history.getByRole('button',{name:'Προβολή',exact:true}).click();
  await expect(history.getByRole('region',{name:'Προβολή δημοσίευσης'})).toContainText('Μαρία');
  for(const secret of ['PRIVATE_EMAIL','PRIVATE_PHONE','PRIVATE_AFM','PRIVATE_AUTH_UID'])await expect(workspace).not.toContainText(secret);
  const download=page.waitForEvent('download');await history.getByRole('button',{name:'Λήψη PDF',exact:true}).click();await download;
  await history.getByRole('button',{name:'Δημιουργία draft από αυτή την έκδοση'}).click();
  await expect(workspace.getByRole('button',{name:'Αφαίρεση βάρδιας'})).toHaveCount(6);
  expect(await page.evaluate(()=>JSON.stringify(window.__historyV3)===window.__originalHistory)).toBe(true);
  await page.evaluate(()=>{
    const store=window.__gasStationSchedulerStore;
    store.setState({employees:store.getState().employees.map(e=>e.id==='a'?{...e,isActive:false}:e)});
  });
  await expect(workspace.getByRole('region',{name:'Προειδοποιήσεις',exact:true})).toContainText('ανενεργό');
  const historicalAssignments=workspace.locator('select option[value="a"]:checked:disabled');
  expect(await historicalAssignments.count()).toBeGreaterThan(0);
  await workspace.getByRole('button',{name:'+ Προσθήκη εργαζομένου',exact:true}).click();
  const pending=workspace.getByRole('group',{name:'Νέα ανάθεση',exact:true});
  await expect(pending.getByRole('combobox',{name:'Εργαζόμενος',exact:true}).locator('option[value="a"]')).toHaveCount(0);
  await pending.getByRole('button',{name:'Ακύρωση',exact:true}).click();
  await expect(workspace.getByRole('button',{name:'Αφαίρεση βάρδιας'})).toHaveCount(6);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
  await workspace.screenshot({path:info.outputPath(`v3-history-${width}.png`)});
  await workspace.getByRole('button',{name:'+ Προσθήκη εργαζομένου',exact:true}).click();
  await workspace.getByRole('button',{name:'Δημιουργία',exact:true}).click();
  await expect(workspace.getByRole('group',{name:'Νέα ανάθεση',exact:true})).toHaveCount(0);
  expect(pageErrors).toEqual([]);
});
