import {test,expect} from 'playwright/test';
import {makeDefaultConfigV3} from '../src/services/schedulerV3Service.ts';
const url=process.env.E2E_BASE_URL||'http://127.0.0.1:5189';
test.setTimeout(90_000);
for(const width of [390,1440])test(`direct workforce profile and fifth employee at ${width}px`,async({page},info)=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width,height:900});await page.goto(url);
  await page.waitForFunction(()=>window.__gasStationSchedulerStore);
  const config=makeDefaultConfigV3('tenant-a');
  config.shiftTemplates[0]={...config.shiftTemplates[0],startTime:'06:00',endTime:'14:00'};
  config.shiftTemplates.push({...config.shiftTemplates[0],id:'alternate',label:'Δεύτερο ωράριο',shiftType:'CUSTOM',startTime:'14:00',endTime:'22:00'});
  config.operatingDays.forEach(d=>{if(d.isOpen)d.windows=[{openTime:'06:00',closeTime:'22:00',crossMidnight:false}];});
  await page.evaluate(async config=>{
    const moduleUrl=path=>performance.getEntriesByType('resource').map(e=>e.name).findLast(url=>new URL(url).pathname===path)||path;
    const {employeesRepository}=await import('/src/repositories/index.js');
    const {schedulePublicationsRepository:repo}=await import(moduleUrl('/src/repositories/schedulePublicationsRepository.ts'));
    const store=window.__gasStationSchedulerStore;store.getState().cleanupData();
    store.setState({isAdmin:true,adminUser:{uid:'fixture-owner',tenantId:'tenant-a'},isLoading:false,isAuthLoading:false,schedulerSchemaVersion:3,schedulerConfigV3:config,employees:Array.from({length:4},(_,n)=>({id:'e'+(n+1),fullName:'Εργαζόμενος '+(n+1),isActive:true,scheduleRole:'CORE_A'})),absences:[],announcements:[]});
    employeesRepository.createEmployee=async payload=>{window.__createdEmployeePayload=payload;return {id:'e5',...payload};};
    store.setState({refreshPublicEmployeesSnapshot:async()=>true});
    repo.saveSettings=async(c,employees)=>{window.__savedProfiles=employees;store.setState({schedulerConfigV3:c,employees:employees.map(e=>({...e}))});};
  },config);
  const workspace=page.getByTestId('scheduler-v3-workspace');await expect(workspace).toBeVisible();
  await workspace.getByText('Ρυθμίσεις και προφίλ εργαζομένων',{exact:true}).click();
  const form=workspace.getByRole('form',{name:'Ρυθμίσεις προγράμματος V3'});
  await expect(form.getByRole('combobox',{name:'Εργαζόμενος',exact:true})).toBeVisible();
  const participation=form.getByRole('combobox',{name:'Συμμετοχή',exact:true});
  expect(await participation.locator('option').allTextContents()).toEqual(['Κανονική συμμετοχή','Μόνο για κάλυψη / αντικατάσταση']);
  await expect(page.getByText(/CORE_A|CORE_B|FLEX_A|FLEX_B|EXTRA_A|EXTRA_B|Core 1|Core 2/)).toHaveCount(0);
  await workspace.getByLabel('Ημερομηνία',{exact:true}).fill('2026-09-07');await workspace.getByRole('button',{name:'Δημιουργία',exact:true}).click();
  await expect(workspace.getByRole('button',{name:'Αφαίρεση βάρδιας'})).toHaveCount(6);
  await workspace.getByText('Εργαζόμενοι και απουσίες',{exact:true}).click();
  await workspace.getByRole('textbox',{name:'Ονοματεπώνυμο',exact:true}).fill('Πέμπτος εργαζόμενος');
  await workspace.getByRole('button',{name:'Προσθήκη εργαζομένου',exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>window.__gasStationSchedulerStore.getState().employees.length)).toBe(5);
  expect(await page.evaluate(()=>window.__createdEmployeePayload.schedulerV3.workMode)).toBe('NORMAL');
  expect(await page.evaluate(()=>window.__createdEmployeePayload.schedulerV3.profileVersion)).toBe(2);
  for(const key of ['scheduleRole','fixedDayOff','participatesInRotation','defaultShiftPreference','weeklyFixedShiftSideRotation'])expect(await page.evaluate(key=>Object.hasOwn(window.__createdEmployeePayload,key),key)).toBe(false);
  await expect(workspace.getByRole('region',{name:'Ώρες εργαζομένων'})).toContainText('Πέμπτος εργαζόμενος: 0 ώρες');
  await workspace.getByRole('button',{name:'Δημιουργία',exact:true}).click();
  await expect(workspace.getByRole('region',{name:'Ώρες εργαζομένων'})).toContainText('Πέμπτος εργαζόμενος: 8 ώρες');
  await form.getByRole('combobox',{name:'Εργαζόμενος',exact:true}).selectOption('e5');
  for(const [start,end]of [['06:00','14:00'],['07:30','15:30'],['22:00','06:00']]){
    await form.getByRole('combobox',{name:'Τυπική έναρξη',exact:true}).selectOption(start);
    await form.getByRole('combobox',{name:'Τυπική λήξη',exact:true}).selectOption(end);
    await expect(form.getByRole('combobox',{name:'Τυπική έναρξη',exact:true})).toHaveValue(start);
    await expect(form.getByRole('combobox',{name:'Τυπική λήξη',exact:true})).toHaveValue(end);
  }
  await form.getByRole('combobox',{name:'Τυπική έναρξη',exact:true}).selectOption('06:00');
  await form.getByRole('combobox',{name:'Τυπική λήξη',exact:true}).selectOption('14:00');
  await form.getByRole('combobox',{name:'Σταθερό ρεπό',exact:true}).selectOption('6');
  await form.getByRole('spinbutton',{name:'Στόχος εβδομαδιαίων ωρών',exact:true}).fill('37.5');
  await form.getByRole('checkbox',{name:'Αλλαγή βάρδιας κάθε εβδομάδα',exact:true}).check();
  await expect(form).toContainText('14:00');
  await page.evaluate(()=>{const store=window.__gasStationSchedulerStore;store.setState({employees:store.getState().employees.map(e=>e.id==='e5'?{...e,fullName:'Πέμπτος (ενημερωμένος)'}:e)});});
  await expect(form.getByRole('combobox',{name:'Εργαζόμενος',exact:true}).locator('option:checked')).toHaveText('Πέμπτος (ενημερωμένος)');
  await form.getByRole('button',{name:'Αποθήκευση ρυθμίσεων',exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>window.__savedProfiles?.find(e=>e.id==='e5')?.schedulerV3.fixedDayOff)).toBe(6);
  const saved=await page.evaluate(()=>window.__savedProfiles.find(e=>e.id==='e5').schedulerV3);
  expect(saved.standardShift).toEqual({startTime:'06:00',endTime:'14:00'});expect(saved.rotationAlternateShift).toEqual({startTime:'14:00',endTime:'22:00'});expect(saved.targetWeeklyHours).toBe(37.5);
  expect(saved).not.toHaveProperty('standardShiftTemplateId');
  await page.evaluate(()=>{
    const store=window.__gasStationSchedulerStore;const config=structuredClone(store.getState().schedulerConfigV3);
    config.shiftTemplates.push({...config.shiftTemplates[0],id:'night',label:'Νυχτερινό',startTime:'22:00',endTime:'06:00',crossMidnight:true});store.setState({schedulerConfigV3:config});
  });
  await form.getByRole('combobox',{name:'Εργαζόμενος',exact:true}).selectOption('e5');
  await expect(form).toContainText('περισσότερες από μία');
  await expect(form.getByRole('button',{name:'Αποθήκευση ρυθμίσεων',exact:true})).toBeDisabled();
  const rotation=form.getByRole('checkbox',{name:'Αλλαγή βάρδιας κάθε εβδομάδα',exact:true});
  await rotation.uncheck();await expect(rotation).toBeDisabled();
  await expect(form.getByText('NORMAL',{exact:true})).toHaveCount(0);await expect(form.getByText('SUBSTITUTE_ONLY',{exact:true})).toHaveCount(0);
  await expect(page.getByText('Πίνακας Ανακοινώσεων',{exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Ιστορικό Προγραμμάτων',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
  await form.screenshot({path:info.outputPath(`direct-profile-${width}.png`)});expect(errors).toEqual([]);
});
