// Real browser with HTTPS origin simulation backed only by local emulators.
// This is NOT hosted acceptance. No credentials or authenticated traces are saved.
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {chromium} from 'playwright';
import {ownerWorkflows} from './owner-workflows.mjs';
import {demoWorkspaceUrlReady} from './browser-route-guard.mjs';
const tenants=['demo-fuel','demo-cafe','demo-salon','demo-market'],domains=new Set(['demo.shiftoryx.gr',...tenants.map(t=>t+'.shiftoryx.gr')]);
const raceTenant=process.argv.find(a=>a.startsWith('--race-tenant='))?.split('=')[1]||'demo-market';
assert.ok(tenants.includes(raceTenant)&&raceTenant!=='demo-cafe','Choose fuel, salon or market for race coverage; cafe is the foreign sentinel.');
const runtimeHealth=await fetch('http://127.0.0.1:5201/',{signal:AbortSignal.timeout(5000)}).catch(()=>null);
if(!runtimeHealth?.ok)throw new Error('Start the public-demo emulator runtime before browser QA.');
const output=await mkdtemp(join(tmpdir(),'shiftoryx-demo-browser-')),browser=await chromium.launch({headless:true});
const results=[];let currentPage;
function record(tenant,scenario,value=true){assert.equal(value,true,tenant+': '+scenario);results.push({tenant,scenario,result:'PASS'});console.log('PASS '+tenant+' '+scenario);}
const canonical=value=>JSON.stringify(value,(_,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item);
async function context(){const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,serviceWorkers:'block'});for(const host of domains)await ctx.grantPermissions(['local-network-access'],{origin:'https://'+host});await ctx.routeWebSocket('**/*',s=>s.close());await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(domains.has(u.hostname)){if(u.pathname==='/__qa-origin'){await route.fulfill({contentType:'text/html',body:'<!doctype html><title>Demo isolated origin test</title>'});return;}await route.fulfill({response:await route.fetch({url:'http://127.0.0.1:5201'+u.pathname+u.search,maxRedirects:0})});return;}if(u.hostname==='127.0.0.1'&&['9308','8197','9408','5111','5201'].includes(u.port)){await route.continue();return;}if(['blob:','data:'].includes(u.protocol)){await route.continue();return;}await route.abort('blockedbyclient');});return ctx;}
async function enter(page,tenant){await page.goto('https://demo.shiftoryx.gr');await page.locator('article#'+tenant).getByRole('button').click();await page.waitForURL(u=>demoWorkspaceUrlReady(u,tenant),{timeout:90000});await page.getByTestId('scheduler-v3-workspace').waitFor({timeout:90000});}
async function publish(workspace,version){const ack=workspace.getByLabel('Διάβασα τις προειδοποιήσεις και επιλέγω δημοσίευση.',{exact:true});if(await ack.count())await ack.check();await workspace.getByRole('button',{name:'Δημοσίευση νέας έκδοσης',exact:true}).click();await workspace.getByText(`Δημοσιεύτηκε η έκδοση ${version}.`,{exact:true}).waitFor({timeout:30000});}
async function snapshot(page,tenant){return page.evaluate(async tenant=>{const {schedulePublicationsRepository:r}=await import('/src/repositories/schedulePublicationsRepository.ts');const p=(await r.list(tenant)).find(p=>p.version===1);return {snapshot:p,bytes:Array.from(new Uint8Array(await r.download(tenant,p.id)))};},tenant);}
try{
  for(const tenant of process.argv.includes('--mutation-retries-only')?['demo-fuel']:process.argv.includes('--races-only')?[raceTenant]:tenants){
    const ctx=await context(),page=await ctx.newPage();currentPage=page;page.setDefaultTimeout(20000);
    const pageErrors=[];ctx.on('page',p=>p.on('pageerror',e=>pageErrors.push(e.name)));page.on('pageerror',e=>pageErrors.push(e.name));
    page.on('requestfailed',request=>{const u=new URL(request.url());if(request.failure()?.errorText!=='net::ERR_ABORTED')console.log('REQUEST_FAILED '+u.hostname+u.pathname+' '+request.failure()?.errorText);});
    page.on('request',request=>{const u=new URL(request.url());if(u.hostname==='127.0.0.1'&&u.port==='5111')console.log('FUNCTION_START '+u.pathname);});
    page.on('response',response=>{const u=new URL(response.url());if(u.hostname==='127.0.0.1'&&(u.port==='5111'||response.status()>=400))console.log('EMULATOR_HTTP '+response.status()+' '+u.port+u.pathname);});
    await enter(page,tenant);record(tenant,'landing selection + custom token + broker redirect');
    if(process.argv.includes('--mutation-retries-only')){const {mutationBrowserRetries}=await import('./mutation-browser-retries.mjs');await mutationBrowserRetries(page,tenant,record);record(tenant,'no unhandled browser errors',pageErrors.length===0);await ctx.close();break;}
    if(process.argv.includes('--races-only')){const {authResetRaces}=await import('./auth-reset-races.mjs');await authResetRaces(page,ctx,tenant,record);record(tenant,'no unhandled browser errors',pageErrors.length===0);await ctx.close();break;}
    if(process.argv.includes('--owners-only')){await ownerWorkflows(page,tenant,record);record(tenant,'no unhandled browser errors',pageErrors.length===0);await ctx.close();continue;}
    await page.reload();await page.getByTestId('scheduler-v3-workspace').waitFor();record(tenant,'refresh retains session');
    const w=page.getByTestId('scheduler-v3-workspace');
    const week=await page.evaluate(async tenant=>{const {db}=await import('/src/firebase/config.js');const url=performance.getEntriesByType('resource').map(e=>e.name).findLast(url=>new URL(url).pathname.endsWith('/firebase_firestore.js'));const fs=await import(url);return (await fs.getDoc(fs.doc(db,'demoState',tenant))).data().weekStart;},tenant);
    await w.getByText('Εργαζόμενοι και απουσίες',{exact:true}).click();record(tenant,'canonical roster visible',await w.getByRole('button',{name:'Επεξεργασία στοιχείων',exact:true}).count()==={'demo-fuel':6,'demo-cafe':8,'demo-salon':6,'demo-market':9}[tenant]);
    await w.getByText('Εργαζόμενοι και απουσίες',{exact:true}).click();
    await w.getByLabel('Ημερομηνία',{exact:true}).fill(week);await w.getByRole('button',{name:'Δημιουργία',exact:true}).click();await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).first().waitFor();
    const count=await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).count();record(tenant,'WEEK generated',count>0);await page.screenshot({path:join(output,tenant+'-week.png')});
    const stats=w.getByRole('region',{name:'Ώρες εργαζομένων',exact:true}),before=await stats.innerText();
    const picker=w.getByRole('combobox',{name:'Από',exact:true}).first();record(tenant,'15-minute time picker',await picker.locator('option').count()===96);await picker.selectOption('06:15');record(tenant,'time edit recalculates actual hours',await stats.innerText()!==before);
    const employee=w.getByRole('combobox',{name:'Εργαζόμενος',exact:true}).first(),old=await employee.inputValue();const replacement=await employee.locator('option').evaluateAll((options,old)=>options.find(o=>o.value!==old&&!o.disabled).value,old);await employee.selectOption(replacement);record(tenant,'employee replacement',await employee.inputValue()===replacement);
    await w.getByRole('button',{name:'+ Προσθήκη εργαζομένου',exact:true}).click();const pending=w.getByRole('group',{name:'Νέα ανάθεση',exact:true});await pending.getByRole('combobox',{name:'Εργαζόμενος',exact:true}).selectOption(replacement);await pending.getByRole('button',{name:'Προσθήκη',exact:true}).click();record(tenant,'manual assignment added',await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).count()===count+1);
    await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).first().click();record(tenant,'assignment removed and warnings visible',await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).count()===count&&(await w.getByRole('region',{name:'Προειδοποιήσεις',exact:true}).innerText()).length>0);
    await publish(w,1);const v1=await snapshot(page,tenant);record(tenant,'publish with warnings',v1.snapshot.publishedWithWarnings);
    await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).first().click();await publish(w,2);record(tenant,'v1 publication and PDF immutable after v2',canonical(await snapshot(page,tenant))===canonical(v1));
    await w.getByRole('button',{name:'Φόρτωση ιστορικού',exact:true}).click();const history=w.getByRole('region',{name:'Ιστορικό δημοσιεύσεων',exact:true});record(tenant,'history shows two versions',await history.getByRole('article').count()===2);
    const downloaded=page.waitForEvent('download');await history.getByRole('button',{name:'Λήψη PDF',exact:true}).last().click();const download=await downloaded;await download.saveAs(join(output,tenant+'-publication.pdf'));record(tenant,'stored PDF downloaded',(await readFile(join(output,tenant+'-publication.pdf'))).subarray(0,5).toString()==='%PDF-');
    await w.getByRole('combobox',{name:'Περίοδος',exact:true}).selectOption('MONTH');await w.getByRole('button',{name:'Δημιουργία',exact:true}).click();record(tenant,'MONTH generated',await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).count()>count);await page.screenshot({path:join(output,tenant+'-month.png')});
    // Auth on a foreign origin must not turn hostname selection into authorization.
    const customToken=await page.evaluate(async tenant=>{const {functions}=await import('/src/firebase/config.js');const url=performance.getEntriesByType('resource').map(e=>e.name).findLast(url=>new URL(url).pathname.endsWith('/firebase_functions.js'));return (await (await import(url)).httpsCallable(functions,'enterPublicDemo')({tenantId:tenant})).data.customToken;},tenant);
    for(const other of tenants.filter(t=>t!==tenant)){const foreign=await ctx.newPage();await foreign.goto('https://'+other+'.shiftoryx.gr/__qa-origin');await foreign.evaluate(async token=>{const {auth}=await import('/src/firebase/config.js');const url=performance.getEntriesByType('resource').map(e=>e.name).findLast(url=>new URL(url).pathname.endsWith('/firebase_auth.js'));await (await import(url)).signInWithCustomToken(auth,token);},customToken);await foreign.goto('https://'+other+'.shiftoryx.gr/app');await foreign.getByText(/Δεν έχετε πρόσβαση|Δεν έχεις πρόσβαση|Δεν επιτρέπεται|δεν έχει πρόσβαση/).first().waitFor();record(tenant,'foreign hostname denied '+other,await foreign.getByTestId('scheduler-v3-workspace').count()===0);await foreign.close();}
    page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Επαναφορά Demo',exact:true}).click();await page.waitForURL(u=>u.hostname==='demo.shiftoryx.gr',{timeout:450000});await enter(page,tenant);record(tenant,'reset and re-enter restore canonical data',await page.getByTestId('scheduler-v3-workspace').count()===1);await page.getByRole('button',{name:'Φόρτωση ιστορικού',exact:true}).click();record(tenant,'reset clears publication history',await page.getByRole('region',{name:'Ιστορικό δημοσιεύσεων',exact:true}).getByRole('article').count()===0);
    await page.getByRole('button',{name:'Αποσύνδεση',exact:true}).click();await page.waitForURL(u=>u.hostname==='demo.shiftoryx.gr');await enter(page,tenant);record(tenant,'logout and re-enter');record(tenant,'no unhandled browser errors',pageErrors.length===0);await ctx.close();
  }
  console.log('PUBLIC_DEMO_BROWSER_PASS '+results.length+' output='+output);
}catch(error){if(currentPage&&!currentPage.isClosed()){await currentPage.screenshot({path:join(output,'failure.png')}).catch(()=>{});console.log('VISIBLE_FAILURE '+(await currentPage.locator('body').innerText()).slice(0,3000));}console.error('BROWSER_FAILURE '+String(error.message).replace(/([?&#](?:token|authTicket)=)[^\s&"']+/gi,'$1[REDACTED]').replace(/\beyJ[A-Za-z0-9_.-]+/g,'[REDACTED]'));process.exitCode=1;}finally{await writeFile(join(output,'results.json'),JSON.stringify({mode:'LOCAL_EMULATOR_NOT_HOSTED',results},null,2));await browser.close();console.log('PUBLIC_DEMO_BROWSER_EVIDENCE='+output);}
