// Actual HTTPS UI acceptance. No localhost routes, mocked API responses,
// credentials in traces, or imports from a development server.
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {chromium} from 'playwright';
import {expect} from 'playwright/test';
const tenants=['demo-fuel','demo-cafe','demo-salon','demo-market'];
const staff={'demo-fuel':6,'demo-cafe':8,'demo-salon':6,'demo-market':9};
const landing='https://demo.shiftoryx.gr';
const output=await mkdtemp(join(tmpdir(),'shiftoryx-hosted-browser-'));
const results=[],browser=await chromium.launch({headless:true});let currentPage;
function record(tenant,scenario){results.push({tenant,scenario,result:'PASS'});console.log('HOSTED_PASS '+tenant+' '+scenario);}
async function enter(page,tenant){await page.goto(landing);await expect(page.locator('article')).toHaveCount(4);await page.locator('article#'+tenant).getByRole('button').click();await page.waitForURL(u=>u.hostname===tenant+'.shiftoryx.gr'&&u.pathname==='/app'&&!u.hash,{timeout:90000});await page.getByTestId('scheduler-v3-workspace').waitFor({timeout:60000});}
async function publish(w,version){const ack=w.getByLabel('Διάβασα τις προειδοποιήσεις και επιλέγω δημοσίευση.',{exact:true});await expect(ack).toBeVisible();await ack.check();await w.getByRole('button',{name:'Δημοσίευση νέας έκδοσης',exact:true}).click();await expect(w.getByText(`Δημοσιεύτηκε η έκδοση ${version}.`,{exact:true})).toBeVisible({timeout:60000});}
async function download(page,article,path){const pending=page.waitForEvent('download',{timeout:60000});await article.getByRole('button',{name:'Λήψη PDF',exact:true}).click();await (await pending).saveAs(path);const bytes=await readFile(path);assert.equal(bytes.subarray(0,5).toString(),'%PDF-');return bytes;}
try{
  for(const tenant of tenants){
    const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,serviceWorkers:'block'}),page=await ctx.newPage();currentPage=page;page.setDefaultTimeout(30000);const errors=[];page.on('pageerror',()=>errors.push('uncaught browser error'));
    await page.goto(landing);await expect(page.locator('article')).toHaveCount(4);if(tenant==='demo-fuel')await page.screenshot({path:join(output,'landing.png'),fullPage:true});
    await enter(page,tenant);record(tenant,'HTTPS landing, selection, login and correct redirect');await page.reload();await page.getByTestId('scheduler-v3-workspace').waitFor();record(tenant,'session persists on refresh');
    await page.goto('https://'+tenant+'.shiftoryx.gr/app');await page.getByTestId('scheduler-v3-workspace').waitFor();record(tenant,'direct authorized subdomain');
    const w=page.getByTestId('scheduler-v3-workspace');await w.getByText('Εργαζόμενοι και απουσίες',{exact:true}).click();await expect(w.getByRole('button',{name:'Επεξεργασία στοιχείων',exact:true})).toHaveCount(staff[tenant]);await w.getByText('Εργαζόμενοι και απουσίες',{exact:true}).click();record(tenant,'canonical employee roster');
    await w.getByRole('button',{name:'Δημιουργία',exact:true}).click();await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).first().waitFor();const count=await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).count();assert.ok(count>0);await page.screenshot({path:join(output,tenant+'-week.png')});record(tenant,'WEEK generation');
    const stats=w.getByRole('region',{name:'Ώρες εργαζομένων',exact:true}),before=await stats.innerText(),picker=w.getByRole('combobox',{name:'Από',exact:true}).first();await expect(picker.locator('option')).toHaveCount(96);await picker.selectOption('06:15');await expect(stats).not.toHaveText(before);record(tenant,'15-minute time edit recalculates hours');
    const employee=w.getByRole('combobox',{name:'Εργαζόμενος',exact:true}).first(),old=await employee.inputValue();const replacement=await employee.locator('option').evaluateAll((options,old)=>options.find(o=>o.value!==old&&!o.disabled).value,old);await employee.selectOption(replacement);await expect(employee).toHaveValue(replacement);record(tenant,'Preview employee replacement');
    await w.getByRole('button',{name:'+ Προσθήκη εργαζομένου',exact:true}).click();const pending=w.getByRole('group',{name:'Νέα ανάθεση',exact:true});await pending.getByRole('combobox',{name:'Εργαζόμενος',exact:true}).selectOption(replacement);await pending.getByRole('button',{name:'Προσθήκη',exact:true}).click();await expect(w.getByRole('button',{name:'Αφαίρεση βάρδιας'})).toHaveCount(count+1);record(tenant,'manual assignment added');
    await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).first().click();await expect(w.getByRole('button',{name:'Αφαίρεση βάρδιας'})).toHaveCount(count);await expect(w.getByRole('region',{name:'Προειδοποιήσεις',exact:true})).toContainText('Κάλυψη');record(tenant,'assignment removal and live coverage warnings');
    await publish(w,1);record(tenant,'publish v1 with warnings');const history=w.getByRole('region',{name:'Ιστορικό δημοσιεύσεων',exact:true});await expect(history.getByRole('article')).toHaveCount(1);const v1=history.getByRole('article').first();await v1.getByRole('button',{name:'Προβολή',exact:true}).click();const view=w.getByRole('region',{name:'Προβολή δημοσίευσης',exact:true}),v1Text=await view.innerText();await view.getByRole('button',{name:'Κλείσιμο προβολής',exact:true}).click();const v1Bytes=await download(page,v1,join(output,tenant+'-v1.pdf'));record(tenant,'stored publication PDF downloaded');
    await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).first().click();await publish(w,2);await w.getByRole('button',{name:'Φόρτωση ιστορικού',exact:true}).click();await expect(history.getByRole('article')).toHaveCount(2);const prior=history.getByRole('article').filter({has:page.getByRole('heading',{level:3,name:/Έκδοση 1$/})});await expect(prior).toHaveCount(1);await prior.getByRole('button',{name:'Προβολή',exact:true}).click();assert.equal(await view.innerText(),v1Text);await view.getByRole('button',{name:'Κλείσιμο προβολής',exact:true}).click();const after=await download(page,prior,join(output,tenant+'-v1-after-v2.pdf'));assert.deepEqual(after,v1Bytes);record(tenant,'history v2 leaves v1 snapshot and stored PDF unchanged');
    await w.getByRole('combobox',{name:'Περίοδος',exact:true}).selectOption('MONTH');await w.getByRole('button',{name:'Δημιουργία',exact:true}).click();await expect.poll(()=>w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).count()).toBeGreaterThan(count);await expect(stats).toBeVisible();await page.screenshot({path:join(output,tenant+'-month.png')});record(tenant,'MONTH generation and employee totals');
    await w.getByText('Εβδομαδιαίοι στόχοι και αποκλίσεις',{exact:true}).click();await expect(w.getByRole('columnheader',{name:'Στόχος',exact:true})).toBeVisible();record(tenant,'weekly targets and deltas visible');
    // A fresh foreign origin must not inherit this tenant's operational session.
    for(const foreign of tenants.filter(t=>t!==tenant)){const other=await ctx.newPage();await other.goto('https://'+foreign+'.shiftoryx.gr/app');await other.waitForURL(u=>u.hostname==='demo.shiftoryx.gr',{timeout:60000});await expect(other.getByTestId('scheduler-v3-workspace')).toHaveCount(0);record(tenant,'foreign hostname cannot expose '+foreign);await other.close();}
    page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Επαναφορά Demo',exact:true}).click();await page.waitForURL(u=>u.hostname==='demo.shiftoryx.gr',{timeout:450000});await enter(page,tenant);await w.getByText('Εργαζόμενοι και απουσίες',{exact:true}).click();await expect(w.getByRole('button',{name:'Επεξεργασία στοιχείων',exact:true})).toHaveCount(staff[tenant]);await w.getByRole('button',{name:'Φόρτωση ιστορικού',exact:true}).click();await expect(history.getByRole('article')).toHaveCount(0);record(tenant,'Demo Reset restores canonical roster and clears history');
    await page.getByRole('button',{name:'Αποσύνδεση',exact:true}).click();await page.waitForURL(u=>u.hostname==='demo.shiftoryx.gr');await enter(page,tenant);record(tenant,'logout and re-enter');assert.deepEqual(errors,[]);record(tenant,'no uncaught browser errors');await ctx.close();
  }
  console.log('HOSTED_BROWSER_PASS checks='+results.length+' output='+output);
}catch(error){if(currentPage&&!currentPage.isClosed()){await currentPage.screenshot({path:join(output,'failure.png')}).catch(()=>{});console.log('HOSTED_VISIBLE_FAILURE '+(await currentPage.locator('body').innerText()).slice(0,2500));}console.error('HOSTED_BROWSER_FAIL '+String(error.message).replace(/([?&#](?:token|key|authTicket)=)[^\s&"']+/gi,'$1[REDACTED]').replace(/\beyJ[A-Za-z0-9_.-]+/g,'[REDACTED]'));process.exitCode=1;}finally{await writeFile(join(output,'results.json'),JSON.stringify({mode:'ACTUAL_HTTPS',results},null,2));await browser.close();console.log('HOSTED_BROWSER_EVIDENCE='+output);}
