// Real browser + emulator only. Fault injection tests UX, not server authorization.
import assert from 'node:assert/strict';
import {chromium,expect as baseExpect} from 'playwright/test';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {dbAdmin,tenants,close} from './test-support.mjs';
import {isFixedDayOff,resolveEffectiveStandardShift} from '../../src/scheduler-engine-v3/employeeProfile.ts';
import {analyzeDraftV3} from '../../src/services/schedulerV3Service.ts';
import {guardDemoRoute,demoWorkspaceUrlReady} from './browser-route-guard.mjs';
const output=await mkdtemp(join(tmpdir(),'shiftoryx-pdf-browser-')),browser=await chromium.launch({headless:true});
const expect=baseExpect.configure({timeout:90000});
const base='http://127.0.0.1:5111/demo-shiftoryx-public/us-central1/',domains=new Set(['demo.shiftoryx.gr',...tenants.map(t=>t+'.shiftoryx.gr')]);
const results=[],clients=[];let probes=false,traffic=0,pairs=0,currentPage;
let asyncFailure=false;
const closingPages=new WeakSet(),closingContexts=new WeakSet();let pageErrors=0;
async function closePage(page){closingPages.add(page);await page.close();}
async function closeContext(ctx){closingContexts.add(ctx);for(const page of ctx.pages())closingPages.add(page);await ctx.close();}
// Playwright transport errors can contain request headers. Never print them.
process.on('unhandledRejection',()=>{asyncFailure=true;console.error('PDF_BROWSER_ASYNC_REQUEST_FAILED');});
function pass(tenant,name){results.push({tenant,name,result:'PASS'});console.log('PASS '+tenant+' '+name);}
async function context(){const c=await browser.newContext({acceptDownloads:true,serviceWorkers:'block',viewport:{width:1440,height:1000}});c.setDefaultTimeout(30000);c.setDefaultNavigationTimeout(90000);c.on('page',p=>p.on('pageerror',()=>pageErrors++));for(const host of domains)await c.grantPermissions(['local-network-access'],{origin:'https://'+host});await c.routeWebSocket('**/*',s=>s.close());
  const rpcNames=new Set(['enterPublicDemo','createAuthTicket','exchangeAuthTicket','publishPublicDemoPdf','downloadPublicDemoPdf','resetPublicDemo']);
  c.on('request',r=>{const u=new URL(r.url()),name=u.pathname.split('/').at(-1);if(u.port==='5111'&&rpcNames.has(name)&&r.method()==='POST')console.log('QA_RPC_BEGIN='+name);});
  c.on('response',r=>{const u=new URL(r.url()),name=u.pathname.split('/').at(-1);if(u.port==='5111'&&rpcNames.has(name)&&r.request().method()==='POST')console.log('QA_RPC_END='+name+' STATUS='+r.status());});
  c.on('request',r=>{const u=new URL(r.url());if(u.port==='9308'&&u.pathname.endsWith('accounts:signInWithCustomToken'))console.log('QA_AUTH_SIGNIN_BEGIN');});
  c.on('response',r=>{const u=new URL(r.url());if(u.port==='9308'&&u.pathname.endsWith('accounts:signInWithCustomToken'))console.log('QA_AUTH_SIGNIN_END STATUS='+r.status());});
  c.on('requestfailed',r=>{const u=new URL(r.url()),name=u.pathname.split('/').at(-1);if((u.port==='5111'&&rpcNames.has(name))||(u.port==='9308'&&u.pathname.endsWith('accounts:signInWithCustomToken')))console.log('QA_AUTH_OR_RPC_REQUEST_FAILED');});
  c.on('request',r=>{const u=new URL(r.url());if(!probes&&(u.port==='9408'||u.hostname.endsWith('storage.googleapis.com')||u.hostname==='firebasestorage.googleapis.com'||u.searchParams.has('X-Goog-Signature')||u.searchParams.has('token')))traffic++;});
  await c.route('**/*',route=>guardDemoRoute(route,async route=>{const u=new URL(route.request().url());if(domains.has(u.hostname)){if(u.pathname==='/__qa-origin'){await route.fulfill({contentType:'text/html',body:'<!doctype html><title>Isolation probe</title>'});return;}await route.fulfill({response:await route.fetch({url:'http://127.0.0.1:5201'+u.pathname+u.search,maxRedirects:0})});return;}if(u.hostname==='127.0.0.1'&&['9308','8197','9408','5111','5201'].includes(u.port)){await route.continue();return;}if(['blob:','data:'].includes(u.protocol)){await route.continue();return;}await route.abort('blockedbyclient');},closingPages,()=>{asyncFailure=true;console.error('PDF_BROWSER_LIVE_PROXY_FAILED');route.abort('failed').catch(()=>{});},()=>closingContexts.has(c)));return c;}
async function enter(page,tenant){await page.goto('https://demo.shiftoryx.gr');await page.locator('article#'+tenant).getByRole('button').click();try{const completed=page.waitForURL(u=>demoWorkspaceUrlReady(u,tenant),{timeout:90000}).then(()=>page.getByTestId('scheduler-v3-workspace').waitFor({timeout:90000}));const rejected=page.locator('.shiftoryx-demo-error').waitFor({state:'visible',timeout:90000}).then(()=>{throw new Error('Entry rejected');});await Promise.race([completed,rejected]);}catch{const facts=await page.evaluate(()=>({landing:location.origin==='https://demo.shiftoryx.gr',busy:[...document.querySelectorAll('button')].some(b=>b.textContent.includes('Άνοιγμα Demo…')),fixedEntryError:document.body.textContent.includes('Η είσοδος δεν ολοκληρώθηκε. Δοκίμασε ξανά σε λίγο.')})).catch(()=>({contextAvailable:false}));console.log('QA_ENTRY_FAILURE='+JSON.stringify({tenant,...facts}));throw new Error('Demo entry did not reach completed /app handoff');}}
async function prepare(page,week,period='WEEK'){const w=page.getByTestId('scheduler-v3-workspace');await w.getByLabel('Ημερομηνία',{exact:true}).fill(week);await w.getByRole('combobox',{name:'Περίοδος',exact:true}).selectOption(period);await w.getByRole('button',{name:'Δημιουργία',exact:true}).click();await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).first().waitFor();return w;}
async function clickPublish(w){const ack=w.getByLabel('Διάβασα τις προειδοποιήσεις και επιλέγω δημοσίευση.',{exact:true});if(await ack.count())await ack.check();await w.getByRole('button',{name:'Δημοσίευση νέας έκδοσης',exact:true}).click();}
async function published(w,n){await expect(w.locator('p[role="status"][aria-live="polite"]')).toHaveText(`Δημοσιεύτηκε η έκδοση ${n}.`,{timeout:90000});}
async function clientRequest(page,name,body){return page.evaluate(async({name,body,base})=>{const {auth}=await import('/src/firebase/config.js');const r=await fetch(base+name,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await auth.currentUser.getIdToken()},body:JSON.stringify(body),signal:AbortSignal.timeout(90000)});return {status:r.status,code:r.ok?null:(await r.json()).error.code};},{name,body,base});}
async function pending(page,tenant){return page.evaluate(t=>{const s=sessionStorage.getItem('shiftoryx-demo-publication-intent:'+t);return s?JSON.parse(s):null;},tenant);}
try{
  if(process.argv.includes('--entry-only')){
    for(const tenant of tenants){const ctx=await context();for(let n=0;n<5;n++){const page=await ctx.newPage();currentPage=page;await enter(page,tenant);pass(tenant,'focused repeated central entry '+(n+1));await closePage(page);}await closeContext(ctx);}
    assert.equal(asyncFailure,false);assert.equal(pageErrors,0);console.log('PDF_ENTRY_DIAGNOSTIC_PASS checks='+results.length);
  }else{
  for(const tenant of tenants){const ctx=await context(),page=await ctx.newPage();currentPage=page;page.setDefaultTimeout(30000);await enter(page,tenant);await page.reload();await page.getByTestId('scheduler-v3-workspace').waitFor();const state=(await dbAdmin.doc('demoState/'+tenant).get()).data(),w=await prepare(page,state.weekStart);
    let sent=[],lost=true;await page.route(base+'publishPublicDemoPdf',async route=>{try{if(route.request().method()!=='POST'){await route.continue();return;}sent.push(JSON.parse(route.request().postData()));if(lost){lost=false;const r=await route.fetch({timeout:90000});assert.equal(r.status(),200);await route.abort('failed');}else await route.continue();}catch{asyncFailure=true;await route.abort('failed').catch(()=>{});}});
    await clickPublish(w);await expect(w.getByRole('button',{name:'Επανάληψη δημοσίευσης',exact:true})).toBeVisible();const tuple=await pending(page,tenant);assert.deepEqual(Object.keys(tuple).sort(),['intentId','draftId','draftRevision','previewHash','acceptWarnings','tenant','generation'].sort());
    const d=(await dbAdmin.doc(`tenants/${tenant}/scheduleDrafts/${tuple.draftId}`).get()).data(),shifts=(await dbAdmin.collection(`tenants/${tenant}/shifts`).get()).docs.filter(s=>d.shiftDocumentIds.includes(s.id)).map(s=>s.data()),draft={...d,shifts},report=analyzeDraftV3(draft);
    assert.ok(shifts.every(s=>!isFixedDayOff(s.date,d.employees.find(e=>e.id===s.employeeId).schedulerV3.fixedDayOff)));assert.ok(shifts.every(s=>!d.absences.some(a=>a.employeeId===s.employeeId&&a.startDate<=s.date&&a.endDate>=s.date)));assert.ok(report.weeklyHours.some(h=>h.delta!==0));
    if(tenant==='demo-fuel')assert.ok(shifts.some(s=>d.employees.find(e=>e.id===s.employeeId).schedulerV3.workMode==='SUBSTITUTE_ONLY'));
    if(tenant==='demo-cafe')assert.ok(report.warnings.some(w=>w.code==='COVERAGE_UNDER_TARGET'));
    if(tenant==='demo-salon'){assert.equal(d.absences.length,0);assert.ok(shifts.every(s=>![0,1].includes(new Date(s.date+'T00:00:00Z').getUTCDay())));assert.ok(d.employees.filter(e=>e.schedulerV3.rotateStandardShiftWeekly).length>=2);}
    if(tenant==='demo-market'){assert.equal(new Set(shifts.map(s=>s.date)).size,7);const sat=d.config.coverageRequirements.find(s=>s.weekday==='SATURDAY'),sun=d.config.coverageRequirements.find(s=>s.weekday==='SUNDAY');assert.notDeepEqual(sat.slots.map(s=>s.headcount),sun.slots.map(s=>s.headcount));}
    pass(tenant,'realistic untouched generated WEEK constraints and soft targets');
    const ack=w.getByLabel('Διάβασα τις προειδοποιήσεις και επιλέγω δημοσίευση.',{exact:true});await ack.uncheck();await expect(w.getByRole('button',{name:'Επανάληψη δημοσίευσης',exact:true})).toBeDisabled();assert.equal(sent.length,1);await ack.check();assert.deepEqual(await pending(page,tenant),tuple);pass(tenant,'revoked acknowledgement blocks retry without losing stable intent');
    const original=(await dbAdmin.collection(`tenants/${tenant}/schedulePublications`).get()).docs;assert.equal(original.length,1);const p1=original[0].data(),before=JSON.stringify(p1);
    await page.reload();await w.waitFor();await expect(w.getByRole('button',{name:'Επανάληψη δημοσίευσης',exact:true})).toBeVisible();assert.deepEqual(await pending(page,tenant),tuple);await w.getByRole('button',{name:'Επανάληψη δημοσίευσης',exact:true}).click();await published(w,1);assert.deepEqual(sent[0],sent[1]);assert.equal((await dbAdmin.collection(`tenants/${tenant}/schedulePublications`).get()).size,1);assert.equal(await pending(page,tenant),null);pass(tenant,'successful finalization lost response + reload + exact replay no duplicate');
    await page.unroute(base+'publishPublicDemoPdf');const pdf=page.waitForEvent('download');await w.getByRole('button',{name:'Λήψη PDF',exact:true}).click();const download=await pdf;assert.equal(download.suggestedFilename(),`schedule-${p1.periodKey}-v1.pdf`);await download.saveAs(join(output,tenant+'-v1.pdf'));pass(tenant,'server Content-Disposition browser download');
    await w.getByRole('button',{name:'Αφαίρεση βάρδιας'}).first().click();await clickPublish(w);await published(w,2);assert.equal(JSON.stringify((await dbAdmin.doc(`tenants/${tenant}/schedulePublications/${p1.id}`).get()).data()),before);pass(tenant,'v1 remains immutable after edited v2');
    await prepare(page,state.weekStart,'MONTH');await clickPublish(w);await published(w,1);const month=(await dbAdmin.collection(`tenants/${tenant}/schedulePublications`).get()).docs.map(s=>s.data()).find(p=>p.periodType==='MONTH');assert.ok(month);const monthDraft=(await dbAdmin.doc(`tenants/${tenant}/scheduleDrafts/${month.sourceDraftId}`).get()).data();for(const e of monthDraft.employees.filter(e=>e.schedulerV3.rotateStandardShiftWeekly)){const matches=month.shifts.filter(s=>s.employeeId===e.id).filter(s=>{const pref=resolveEffectiveStandardShift(e.schedulerV3,s.date);return pref?.startTime===s.startTime&&pref?.endTime===s.endTime;});assert.ok(matches.length>0);assert.ok(new Set(matches.map(s=>s.startTime)).size>=2);}
    await page.screenshot({path:join(output,tenant+'-month.png')});pass(tenant,'MONTH publication and independent rotation preferences');
    clients.push({tenant,ctx,page,p1,tuple,state});await closeContext(ctx);
  }
  for(const c of clients){c.ctx=await context();c.page=await c.ctx.newPage();currentPage=c.page;await enter(c.page,c.tenant);for(const foreign of clients.filter(f=>f!==c)){
    if(c.page.isClosed()){c.page=await c.ctx.newPage();currentPage=c.page;await enter(c.page,c.tenant);}
    assert.equal((await clientRequest(c.page,'downloadPublicDemoPdf',{publicationId:foreign.p1.id})).status,404);
    assert.equal((await clientRequest(c.page,'downloadPublicDemoPdf',{publicationId:c.p1.id})).status,200);
    assert.equal((await clientRequest(c.page,'publishPublicDemoPdf',{...Object.fromEntries(['intentId','draftId','draftRevision','previewHash','acceptWarnings'].map(k=>[k,foreign.tuple[k]])),intentId:crypto.randomUUID()})).status,409);
    const codes=await c.page.evaluate(async({tenant,id})=>{const {schedulePublicationsRepository:r}=await import('/src/repositories/schedulePublicationsRepository.ts');const errors=[];for(const op of [()=>r.list(tenant),()=>r.loadDraft(tenant,id)]){try{await op();errors.push('ALLOWED');}catch(e){errors.push(e.code);}}return errors;},{tenant:foreign.tenant,id:foreign.tuple.draftId});assert.deepEqual(codes,['permission-denied','permission-denied']);
    const token=await c.page.evaluate(async tenant=>{const {functions}=await import('/src/firebase/config.js');const u=performance.getEntriesByType('resource').map(e=>e.name).findLast(u=>new URL(u).pathname.endsWith('/firebase_functions.js'));return (await (await import(u)).httpsCallable(functions,'enterPublicDemo')({tenantId:tenant})).data.customToken;},c.tenant);
    await closePage(c.page);const p=await c.ctx.newPage();currentPage=p;await p.goto('https://'+foreign.tenant+'.shiftoryx.gr/__qa-origin');await p.evaluate(async token=>{const {auth}=await import('/src/firebase/config.js');const u=performance.getEntriesByType('resource').map(e=>e.name).findLast(u=>new URL(u).pathname.endsWith('/firebase_auth.js'));await (await import(u)).signInWithCustomToken(auth,token);},token);await p.goto('https://'+foreign.tenant+'.shiftoryx.gr/app');await p.getByText(/Δεν έχετε πρόσβαση|Δεν έχεις πρόσβαση|Δεν επιτρέπεται|δεν έχει πρόσβαση/).first().waitFor();assert.equal(await p.getByTestId('scheduler-v3-workspace').count(),0);await closePage(p);pairs++;pass(c.tenant,'foreign hostname/history/draft/publish/PDF denied '+foreign.tenant);
  }await closeContext(c.ctx);}assert.equal(pairs,12);
  // Separate intentional bypass probes; excluded from application traffic count.
  for(const c of clients){c.ctx=await context();c.page=await c.ctx.newPage();currentPage=c.page;await enter(c.page,c.tenant);probes=true;try{
    const paths=[`tenants/${c.tenant}/schedulePublicationCounters/${c.p1.periodKey}`,`tenants/${c.tenant}/schedulePublicationReservations/${c.p1.id}`,`tenants/${c.tenant}/schedulePublications/${c.p1.id}`,`tenants/${c.tenant}/schedulePublicationPeriods/${c.p1.periodKey}`,`demoPdfControls/${c.tenant}`,`demoPdfRequests/${c.tenant}/intents/${c.tuple.intentId}`,`demoPdfLimits/${c.tenant}`,`tenants/${c.tenant}/demoPublicationArtifacts/${c.p1.id}`];
    for(const collection of ['publicSchedules','publicMonths']){const docs=await dbAdmin.collection(`tenants/${c.tenant}/${collection}`).get();assert.ok(docs.size);paths.push(docs.docs[0].ref.path);}
    const payload=await Promise.all(paths.map(async path=>{let data=(await dbAdmin.doc(path).get()).data();if(!data){assert.equal(path,`demoPdfControls/${c.tenant}`,'Only the released control is expected to be absent');data={operationId:crypto.randomUUID(),attemptId:crypto.randomUUID(),kind:'PUBLISH',generation:c.state.generation,stage:'RESERVED',startedAt:Date.now(),heartbeatAt:Date.now()};}return {path,data};}));
    const denied=await c.page.evaluate(async({payload,path})=>{const {db,storage}=await import('/src/firebase/config.js');const resources=performance.getEntriesByType('resource').map(e=>e.name),fs=await import(resources.findLast(u=>new URL(u).pathname.endsWith('/firebase_firestore.js'))),st=await import(resources.findLast(u=>new URL(u).pathname.endsWith('/firebase_storage.js')));const codes=[];for(const p of payload){try{await fs.setDoc(fs.doc(db,p.path),p.data);codes.push('ALLOWED');}catch(e){codes.push(e.code);}}for(const op of [()=>st.getBytes(st.ref(storage,path)),()=>st.uploadBytes(st.ref(storage,path),new TextEncoder().encode('%PDF-1.3\n%%EOF'),{contentType:'application/pdf'})]){try{await op();codes.push('ALLOWED');}catch(e){codes.push(e.code);}}return codes;},{payload,path:`tenants/${c.tenant}/schedule-publications/${c.p1.id}/schedule.pdf`});assert.deepEqual(denied,[...paths.map(()=> 'permission-denied'),'storage/unauthorized','storage/unauthorized']);
    pass(c.tenant,'valid direct lifecycle payloads + Storage read/write denied');
  }finally{probes=false;await closeContext(c.ctx);}}
  const c=clients[0];c.ctx=await context();c.page=await c.ctx.newPage();currentPage=c.page;await enter(c.page,c.tenant);const w=c.page.getByTestId('scheduler-v3-workspace');
  // Fault-injected responses must be safe, bounded and require explicit action.
  for(const [code,status,retryable] of [['UNAUTHENTICATED',401,false],['ACCESS_DENIED',403,false],['PREVIEW_CHANGED',409,false],['INTENT_CONFLICT',409,false],['PDF_BUSY',409,true],['DEMO_GENERATION_CHANGED',409,false],['PAYLOAD_TOO_LARGE',413,false],['RATE_LIMITED',429,true],['DEMO_RESETTING',503,true],['PDF_RECOVERY_REQUIRED',503,false]]){
    await prepare(c.page,c.state.weekStart);let attempts=0;await c.page.route(base+'publishPublicDemoPdf',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}attempts++;await route.fulfill({status,headers:{'Access-Control-Allow-Origin':'https://demo-fuel.shiftoryx.gr','Content-Type':'application/json'},body:JSON.stringify({error:{code,message:'UNSAFE_PROVIDER_DETAIL'}})});});await clickPublish(w);await expect(w.locator('p[role="status"][aria-live="polite"]')).not.toHaveText('Επεξεργασία…');assert.equal(attempts,code==='UNAUTHENTICATED'?2:1);assert.equal((await w.innerText()).includes('UNSAFE_PROVIDER_DETAIL'),false);await expect(w.getByRole('button',{name:'Επανάληψη δημοσίευσης',exact:true})).toHaveCount(retryable?1:0);await c.page.unroute(base+'publishPublicDemoPdf');pass(c.tenant,'fault UX '+code+' bounded/no raw details');
  }
  await prepare(c.page,c.state.weekStart);const editedRequests=[];await c.page.route(base+'publishPublicDemoPdf',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}editedRequests.push(JSON.parse(route.request().postData()));await route.fulfill({status:409,headers:{'Access-Control-Allow-Origin':'https://demo-fuel.shiftoryx.gr','Content-Type':'application/json'},body:JSON.stringify({error:{code:'PDF_BUSY'}})});});await clickPublish(w);await expect(w.getByRole('button',{name:'Επανάληψη δημοσίευσης',exact:true})).toBeVisible();await w.getByRole('combobox',{name:'Από',exact:true}).first().selectOption('06:15');assert.equal(await pending(c.page,c.tenant),null);await clickPublish(w);await expect(w.getByRole('button',{name:'Επανάληψη δημοσίευσης',exact:true})).toBeVisible();assert.equal(editedRequests.length,2);assert.notEqual(editedRequests[0].intentId,editedRequests[1].intentId);assert.notEqual(editedRequests[0].previewHash,editedRequests[1].previewHash);await c.page.unroute(base+'publishPublicDemoPdf');pass(c.tenant,'editing unresolved preview discards old intent and explicit publish creates new intent');
  await prepare(c.page,c.state.weekStart);let attempts=0;await c.page.route(base+'publishPublicDemoPdf',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}if(++attempts===1)await route.fulfill({status:401,headers:{'Access-Control-Allow-Origin':'https://demo-fuel.shiftoryx.gr','Content-Type':'application/json'},body:JSON.stringify({error:{code:'UNAUTHENTICATED'}})});else await route.continue();});await clickPublish(w);await published(w,3);assert.equal(attempts,2);await c.page.unroute(base+'publishPublicDemoPdf');pass(c.tenant,'401 one refresh then real positive publication');
  // Real reset invalidates generation and pending state, old objects and IDs.
  await closeContext(c.ctx);
  for(const c of clients){c.ctx=await context();c.page=await c.ctx.newPage();currentPage=c.page;await enter(c.page,c.tenant);const w=await prepare(c.page,c.state.weekStart);await c.page.route(base+'publishPublicDemoPdf',async route=>route.request().method()==='POST'?route.abort('failed'):route.continue());await clickPublish(w);await expect(w.getByRole('button',{name:'Επανάληψη δημοσίευσης',exact:true})).toBeVisible();await c.page.unroute(base+'publishPublicDemoPdf');
    c.page.once('dialog',d=>d.accept());await c.page.getByRole('button',{name:'Επαναφορά Demo',exact:true}).click();await c.page.waitForURL(u=>u.hostname==='demo.shiftoryx.gr',{timeout:450000});await enter(c.page,c.tenant);assert.equal(await pending(c.page,c.tenant),null);assert.equal((await clientRequest(c.page,'downloadPublicDemoPdf',{publicationId:c.p1.id})).status,404);assert.equal((await dbAdmin.collection(`tenants/${c.tenant}/schedulePublications`).get()).size,0);pass(c.tenant,'reset pending/generation/history/old PDF invalidation + re-entry');await closeContext(c.ctx);}
  assert.equal(traffic,0);pass('all','DIRECT_BROWSER_STORAGE_PUBLICATION_TRAFFIC=ZERO (security probes separately classified)');
  assert.equal(asyncFailure,false,'No suppressed async route failure');
  assert.equal(pageErrors,0,'No unhandled application page errors');
  console.log('PDF_CLIENT_BROWSER_PASS checks='+results.length+' orderedPairs='+pairs+' output='+output);
  }
}catch(e){console.error('PDF_BROWSER_FAILURE '+String(e.message).replace(/\beyJ[A-Za-z0-9_.-]+/g,'[REDACTED]').replace(/([?&#]authTicket=)[^\s&"']+/g,'$1[REDACTED]'));if(currentPage&&!currentPage.isClosed())await currentPage.screenshot({path:join(output,'failure.png')});process.exitCode=1;}finally{await writeFile(join(output,'results.json'),JSON.stringify({scope:'LOCAL_EMULATOR_NOT_HOSTED',results,applicationStorageTraffic:traffic,pairs},null,2));for(const ctx of browser.contexts())await closeContext(ctx);await browser.close();await close();}
